# Generated by Django 5.1 on 2024-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='cpf_cnpj_cliente',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='nome_cliente',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
