# Generated by Django 5.1.1 on 2024-09-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='data_orcamento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
