# Generated by Django 5.1.1 on 2024-09-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budget_data_orcamento'),
        ('client', '0005_rename_cpf_cnpj_cliente_client_cpf_cnpj_and_more'),
        ('employee', '0002_alter_employee_cargo_alter_employee_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='number_budget',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BudgetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_budget', models.IntegerField(null=True)),
                ('data_orcamento', models.DateField(auto_now_add=True)),
                ('cpf_cnpj_cliente', models.CharField(blank=True, max_length=14, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
    ]
