# Generated by Django 5.1.1 on 2024-09-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budget_number_budget_budgetinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTempBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_produto', models.IntegerField(blank=True, null=True)),
                ('name_product', models.CharField(max_length=70)),
                ('quantidade', models.FloatField(null=True)),
                ('valor_uni', models.FloatField(null=True)),
                ('valor_total', models.FloatField(null=True)),
            ],
        ),
    ]
