# Generated by Django 5.0.13 on 2025-03-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70, null=True)),
                ('descricao', models.CharField(blank=True, max_length=70, null=True)),
                ('estoque', models.FloatField(null=True)),
                ('categoria', models.CharField(blank=True, max_length=70, null=True)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_minima_estoque', models.FloatField(blank=True, null=True)),
                ('unidade_medida', models.CharField(blank=True, max_length=2, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=70, null=True)),
                ('localizacao_estoque', models.CharField(blank=True, max_length=70, null=True)),
                ('status_produto', models.BooleanField(default=True)),
                ('garantia', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao_adicional', models.CharField(blank=True, max_length=255, null=True)),
                ('fornecedor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
            ],
        ),
    ]
