# Generated by Django 5.1 on 2024-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='categoria',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='descricao',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='estoque',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='garantia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='localizacao_estoque',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nome',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='observacao_adicional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantidade_minima_estoque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status_produto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
