# Generated by Django 5.1 on 2024-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('nome_fantasia', models.TextField(blank=True, null=True)),
                ('cpf_cliente', models.TextField(blank=True, null=True)),
                ('cnpj_cliente', models.TextField(blank=True, null=True)),
                ('rg_cliente', models.TextField(blank=True, null=True)),
                ('inscricao_estadual_cliente', models.TextField(blank=True, null=True)),
                ('telefone_contato', models.TextField(blank=True, null=True)),
                ('telefone_celular', models.TextField(blank=True, null=True)),
                ('numero_casa', models.TextField(blank=True, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField(blank=True, null=True)),
                ('cidade', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
