# Generated by Django 5.0.13 on 2025-03-25 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('cpf_cnpj', models.CharField(max_length=14, null=True, unique=True)),
                ('rg', models.CharField(max_length=15, null=True)),
                ('rua', models.CharField(max_length=90, null=True)),
                ('numero_casa', models.IntegerField(null=True)),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=70, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
