# Generated by Django 5.1 on 2024-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cnpj_cliente',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cpf_cliente',
        ),
        migrations.RemoveField(
            model_name='client',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telefone_celular',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telefone_contato',
        ),
        migrations.AddField(
            model_name='client',
            name='cpf_cnpj_cliente',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bairro',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='inscricao_estadual_cliente',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nome',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_casa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg_cliente',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
