# Generated by Django 5.1 on 2024-09-08 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cpf_cnpj_cliente',
            new_name='cpf_cnpj',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='inscricao_estadual_cliente',
            new_name='ie',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='rg_cliente',
            new_name='rg',
        ),
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='rua',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
