# Generated by Django 5.1 on 2024-10-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_cpf_cnpj_cliente_client_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ie',
        ),
        migrations.AddField(
            model_name='client',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
