# Generated by Django 5.1.1 on 2024-10-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nota', models.IntegerField(null=True)),
                ('nome', models.CharField(max_length=70, null=True)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('vencimento', models.DateField(auto_now_add=True)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
