# Generated by Django 5.1.1 on 2024-10-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nota', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=70)),
                ('cnpj', models.CharField(max_length=14)),
                ('vencimento', models.DateField()),
                ('data_venda', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
