# Generated by Django 5.1 on 2024-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nome',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
