# Generated by Django 5.1 on 2024-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='nome_fornecedor',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='numero_nota',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
