# Generated by Django 5.1 on 2024-09-25 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0002_alter_nfe_cnpj_alter_nfe_nome_fornecedor_and_more'),
        ('supplier', '0002_remove_supplier_telefone_alter_supplier_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfe',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='nfe',
            name='total',
        ),
        migrations.AlterField(
            model_name='nfe',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='data_entrada',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='NFEInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=70, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('numero_nota', models.CharField(blank=True, max_length=20, null=True)),
                ('quantidade_itens', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
            ],
        ),
    ]
