# Generated by Django 5.1 on 2024-09-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0003_remove_nfe_nome_produto_remove_nfe_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFECartTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonecedor', models.IntegerField(blank=True, null=True)),
                ('id_produto', models.IntegerField(blank=True, null=True)),
                ('name_product', models.CharField(max_length=70)),
                ('quantidade', models.FloatField(null=True)),
                ('valor_uni', models.FloatField(null=True)),
                ('valor_total', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nfe',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='nfe',
            name='nome_fornecedor',
        ),
        migrations.RemoveField(
            model_name='nfeinfo',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='nfeinfo',
            name='nome_fornecedor',
        ),
    ]
