# Generated by Django 5.1.2 on 2024-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0004_nfecarttemp_remove_nfe_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeinfo',
            name='boleto',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
