# Generated by Django 5.1 on 2024-10-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0006_remove_client_ie_client_cep_alter_client_id'),
        ('sale', '0007_saleinfo_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('num_sale', models.IntegerField(null=True)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('cpf_cnpj', models.CharField(max_length=14, null=True)),
                ('valor', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receive.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('cpf_cnpj', models.CharField(max_length=14, null=True)),
                ('status', models.CharField(max_length=14, null=True)),
                ('valor', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('num_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.saleinfo')),
                ('tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receive.paymenttype')),
            ],
        ),
    ]
