# Generated by Django 5.1 on 2024-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
