# Generated by Django 5.1 on 2024-10-09 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_telefone_alter_supplier_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='endereco',
            new_name='rua',
        ),
        migrations.AddField(
            model_name='supplier',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cidade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
