# Generated by Django 5.1.1 on 2024-10-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_supplier_bairro_alter_supplier_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
