# Generated by Django 5.1 on 2024-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_cpf_cnpj_cliente_alter_sale_nome_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_produto', models.IntegerField(blank=True, null=True)),
                ('name_product', models.CharField(max_length=70)),
                ('quantidade', models.FloatField(null=True)),
                ('valor_uni', models.FloatField(null=True)),
                ('valor_total', models.FloatField(null=True)),
            ],
        ),
    ]
