# Generated by Django 5.1 on 2024-09-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_carttemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.AddField(
            model_name='sale',
            name='num_sale',
            field=models.IntegerField(null=True),
        ),
    ]
