
# Generated by Django 5.1.1 on 2024-09-23 22:43


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_cargo_alter_employee_nome_and_more'),
        ('sale', '0006_alter_sale_data_venda_saleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinfo',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
